'use strict';

/**
 * Generated by vanilla-scripts/generate-config-examples.js
 * Copy this file to a local config file or use it as an env checklist.
 * Do not put real secrets in this example file.
 */
(function () {
	const service = {
		name: "vanilla-medical-body-server",
		port: 3024,
		folder: "vanilla-medical-body-server",
		webRoot: "vanilla-web/vanilla-medical-body-server",
		public: true,
		subdomain: "medical",
		auth: "",
		features: {
		  "static": true,
		  "authRoutes": false,
		  "health": false,
		  "commonApi": false,
		  "serviceRouters": true,
		  "clientLibs": false,
		  "moduleServer": false,
		  "dynamicApi": false,
		  "devLiveReload": false,
		  "proxy": false,
		  "access": false,
		  "honeypot": false
		},
		utilityGroups: []
	};

	const env = {
		// server bind host
		HOST: process.env.HOST || "127.0.0.1",
		// logger level
		LOG_LEVEL: process.env.LOG_LEVEL || "INFO",
		// medical FHIR proxy; detected in service source
		MEDICAL_BODY_ALLOWED_ORIGINS: process.env.MEDICAL_BODY_ALLOWED_ORIGINS || "",
		// medical FHIR proxy; detected in service source
		MEDICAL_FHIR_PROXY_ALLOWLIST: process.env.MEDICAL_FHIR_PROXY_ALLOWLIST || "hapi.fhir.org",
		// medical FHIR proxy; detected in service source
		MEDICAL_FHIR_PROXY_MAX_BYTES: process.env.MEDICAL_FHIR_PROXY_MAX_BYTES || "5242880",
		// medical FHIR proxy; detected in service source
		MEDICAL_FHIR_PROXY_MAX_URL_LENGTH: process.env.MEDICAL_FHIR_PROXY_MAX_URL_LENGTH || "2048",
		// medical FHIR proxy; detected in service source
		MEDICAL_FHIR_PROXY_TIMEOUT_MS: process.env.MEDICAL_FHIR_PROXY_TIMEOUT_MS || "8000",
		// node runtime
		NODE_ENV: process.env.NODE_ENV || "development",
		// service listen port
		PORT: process.env.PORT || "3024",
		// vanilla server bind host
		VANILLA_BIND_HOST: process.env.VANILLA_BIND_HOST || "127.0.0.1",
		// portable data dir override
		VANILLA_DATA_DIR: process.env.VANILLA_DATA_DIR || ".data",
		// gateway main domain
		VANILLA_GATEWAY_DOMAIN: process.env.VANILLA_GATEWAY_DOMAIN || "chlehdwns.dev",
		// parallel local service port offset
		VANILLA_PORT_OFFSET: process.env.VANILLA_PORT_OFFSET || "0",
		// public service runtime marker
		VANILLA_PUBLIC_DEMO: process.env.VANILLA_PUBLIC_DEMO || "1",
		// portable root override
		VANILLA_ROOT_DIR: process.env.VANILLA_ROOT_DIR || ".",
		// service-manager injected service name
		VANILLA_SERVICE_NAME: process.env.VANILLA_SERVICE_NAME || "vanilla-medical-body-server",
		// serve built web dist when enabled
		VANILLA_WEB_DIST: process.env.VANILLA_WEB_DIST || "0"
	};

	const policy = {
	  "public": true,
	  "subdomain": "medical",
	  "auth": "",
	  "codeDelivery": null,
	  "gateway": {
	    "host": "medical.chlehdwns.dev",
	    "auth": "none"
	  }
	};

	module.exports = {
		service: service,
		env: env,
		policy: policy,
		requiredSecrets: [],
		optionalSecrets: []
	};
}());
